use k8s_openapi::api::core::v1::Node;

pub struct NodeStats {
    resource: String,
    r#type: String,
    age: String,
    container_runtime_version: String,
    containers_init: i16,
    containers_ready: i16,
    containers_running: i16,
    containers_terminated: i16,
    containers_total: i16,
    containers_waiting: i16, 
    cpu_allocatable: String,
    cpu_capacity: String,
    cpu_usage: String,
    created: String,
    ip_external: String,
    ip: String,
    kernel_version: String,
    kubelet_version: String,
    memory_allocatable: String,
    memory_capacity: String,
    memory_usage: String,
    node: String,
    os_image: String,
    pods_failed: String,
    pods_pending: i16,
    pods_running: i16,
    pods_succeeded: i16,
    pods_total: i16,
    pods_unknown: i16,
    ready_heartbeat_age: String,
    ready_heartbeat_time: String,
    ready_message: String,
    ready_status: String,
    ready_transition_age: String,
    ready_transition_time: String,
    ready: String,
    unschedulable: String
}

impl NodeStats {

    pub fn build(n: Node) -> NodeStats {
        NodeStats {
            resource: todo!(),
            r#type: todo!(),
            age: todo!(),
            container_runtime_version: todo!(),
            containers_init: todo!(),
            containers_ready: todo!(),
            containers_running: todo!(),
            containers_terminated: todo!(),
            containers_total: todo!(),
            containers_waiting: todo!(),
            cpu_allocatable: todo!(),
            cpu_capacity: todo!(),
            cpu_usage: todo!(),
            created: todo!(),
            ip_external: todo!(),
            ip: todo!(),
            kernel_version: todo!(),
            kubelet_version: todo!(),
            memory_allocatable: todo!(),
            memory_capacity: todo!(),
            memory_usage: todo!(),
            node: todo!(),
            os_image: todo!(),
            pods_failed: todo!(),
            pods_pending: todo!(),
            pods_running: todo!(),
            pods_succeeded: todo!(),
            pods_total: todo!(),
            pods_unknown: todo!(),
            ready_heartbeat_age: todo!(),
            ready_heartbeat_time: todo!(),
            ready_message: todo!(),
            ready_status: todo!(),
            ready_transition_age: todo!(),
            ready_transition_time: todo!(),
            ready: todo!(),
            unschedulable: todo!(),
        }
    }
}