pub struct ClusterStats {
    containers_init: i16,
    containers_ready: i16,
    containers_running: i16,
    containers_terminated: i16,
    containers_total: i16,
    containers_waiting: i16,
    cpu_allocatable: i16,
    cpu_capacity: i16,
    cpu_usage: i16,
    memory_allocatable: i16,
    memory_capacity: i16,
    memory_usage: i16,
    nodes_notready: i16,
    nodes_ready: i16,
    nodes_total: i16,
    nodes_unschedulable: i16,
    pods_allocatable: i16,
    pods_capacity: i16,
    pods_failed: i16,
    pods_pending: i16,
    pods_running: i16,
    pods_succeeded: i16,
    pods_unknown: i16,
    pods_total: i16
}